name: uas_katalog_produk
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^latest_version
  injectable: ^2.4.0
  get_it: ^7.6.7
  bloc: ^8.1.4
  hydrated_bloc: ^9.1.5
  flutter_bloc: ^8.1.6
  floor: ^1.5.0
  sqflite: ^2.4.0
  equatable: ^2.0.5
  path_provider: ^2.1.4
  firebase_core: ^3.6.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9




flutter:
  uses-material-design: true
  assets:
  - assets/

